title: Hello! I'm Developer MyeongHun
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "https://audgns722.github.io/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Developer Hoon # add your name
author-img: profile.jpg # add your photo
about-author: 계획을 세우고 이를 따라가는 것을 좋아하며, 조용한 집중력으로 세세한 부분까지 신경 쓰는 것을 즐깁니다. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: https://github.com/audgns722 # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: audgns722@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
